### ISSUE TITLE
No issue, feature request

### ISSUE THREAD

**Issue by mame82** [thugcrowd/bettercap-loader#1]
Could you exchange `bettercap` with `bettercap "$@"`.

Would have sent a PR, but cloning the repo takes ages (considering the lines and lines of code, no surprise).

Also, once semantic versioning is added, I'd be happy to see a library version, which could be added to other wrappers, in order to ease things up (f.e. removing custom arguments).

Thx for you work

**Comment by mame82** [comment]
Oh ... please add a tag for "meaningful contributions".

Also a contributors list, where you should add me, otherwise I would be required to really contribute code.

**Comment by netspooky** [comment]
Your request was granted. When this package is pulled into the mainline Kali/Parrot/BlackArch repos, we will add the additional semantic versioning features.

**Comment by mame82** [comment]
Please re-open ... there's still no label with "meaningful contribution" assigned.

Otherwise, I wouldn't be able to use the filter function to find my issue again.

Planning to link it in StackExchange to push my career.

Be fair, I spent a shitload of time wrapping my head around how to get your project included in major Linux distros.
