### ISSUE TITLE
Theming support 🎨

### ISSUE THREAD

**Issue by digitalrane** [thugcrowd/bettercap-loader#2]
I don't like the dark background it makes me feel like I'm doing something illegal. I don't want my mum to think I'm a hacker. Please add the ability to theme bettercap-loader, so I can use it in my Sanrio-themed terminal 👋😻.

**Comment by netspooky** [comment]
The theme you have requested has been added. Any new themes will require significant code refactoring, which is out of scope for our dev team. Please submit a PR for any new theme requests. Specify your theme using .bclrc, located in the root of this repo.
